apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajit0211-deploy
  labels:
    app: lalmon149-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lalmon149-mvn-app
  template:
    metadata:
      labels:
        app: lalmon149-mvn-app
    spec:
      containers:
      - name: ajit0211-mvn-container
        image: ajit0211eta/ajit0211devops:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ajit0211-np-service
  labels:
    app: lalmon149-mvn-app
spec:
  selector:
    app: lalmon149-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
